# Generated by Django 6.0.3 on 2026-03-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modrole',
            name='actions_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modrole',
            name='last_action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modrole',
            name='total_actions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modrole',
            name='granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modrole',
            name='status',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('active', 'Active'), ('revoked', 'Revoked')], default='candidate', max_length=20),
        ),
    ]
