# Generated by Django 6.0.3 on 2026-03-05 13:27

import confessions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=64)),
                ('content', models.TextField(max_length=500)),
                ('mood_tag', models.CharField(choices=[('anxious', '😰 Anxious'), ('sad', '😔 Sad'), ('lost', '🌀 Lost'), ('frustrated', '😤 Frustrated'), ('hopeful', '🌱 Hopeful'), ('grateful', '✨ Grateful')], max_length=20)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('career', 'Career'), ('relationships', 'Relationships'), ('health', 'Health'), ('other', 'Other')], max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=confessions.models.default_expiry)),
                ('karma_received', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SessionKarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=64, unique=True)),
                ('karma_points', models.IntegerField(default=0)),
                ('posts_helped', models.IntegerField(default=0)),
                ('week_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=64)),
                ('content', models.TextField(max_length=300)),
                ('is_flagged', models.BooleanField(default=False)),
                ('helpful_votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='confessions.post')),
            ],
        ),
    ]
